lucky-word: "Hello Krish & Anish"

---
spring:
  profiles:
    active: dev

server:
  port: 8761

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

---
spring:
  profiles: aws
server:
  port: 8761
eureka:
  datacenter : cloud
  instance:
    non-secure-port: ${server.port}
      
  client:
    region: us-east-1
    registerWithEureka: true
    fetchRegistry: true
    eurekaServerPort: 8761
    useDnsForFetchingServiceUrls: true
    eureka-server-d-n-s-name: gr8conf.vpc
    eureka-server-u-r-l-context: eureka
  server:
    enable-self-preservation: true
    wait-time-in-ms-when-sync-empty: 0
    bindingStrategy: route53
    
    
